package com.csis3275.Group404Project;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EditUserTypeTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "c:/tmp/chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void editUserTest() {
        driver.get("http://localhost:8080/login");
        driver.manage().window().setSize(new Dimension(1090, 1042));
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("Shubham");
        driver.findElement(By.id("password")).sendKeys("12345");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.cssSelector(".sideButton:nth-child(3)")).click();
        driver.findElement(By.cssSelector("a:nth-child(10)")).click();
        driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(6) > a")).click();
        driver.findElement(By.id("userType")).click();
        {
            WebElement dropdown = driver.findElement(By.id("userType"));
            dropdown.findElement(By.xpath("//option[. = 'User']")).click();
        }
        driver.findElement(By.id("userType")).click();
        driver.findElement(By.id("total")).click();
        driver.findElement(By.id("total")).sendKeys("1200");
        driver.findElement(By.cssSelector("button:nth-child(4)")).click();
        assertThat(driver.findElement(By.xpath("//td[contains(.,\'user\')]")).getText(), is("user"));
    }
}
